<a href="https://colab.research.google.com/github/rcopty/asp360-movie-flop-predictor/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Environment Setup

In [3]:
%pip install -q "kagglehub[pandas-datasets]"

Note: you may need to restart the kernel to use updated packages.

In [4]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import json
import pandas as pd
import numpy as np

/Users/ranacopty/Desktop/APS360/aps360-movie-flop-predictor/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Load the TMDB Datasets

In [5]:
# Load movies file
df_movies = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "tmdb/tmdb-movie-metadata",
  "tmdb_5000_movies.csv"
)

# Load credits file
df_credits = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "tmdb/tmdb-movie-metadata",
  "tmdb_5000_credits.csv"
)

print(df_movies.shape)
print(df_credits.shape)
print(df_movies.columns.tolist())
print(df_credits.columns.tolist())

/var/folders/yq/j2dbx6613tjcnpwcb34hz9vr0000gn/T/ipykernel_37799/2399375892.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_movies = kagglehub.load_dataset(

Downloading to /Users/ranacopty/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/versions/2/tmdb_5000_movies.csv...

100%|██████████| 1.58M/1.58M [00:00<00:00, 14.8MB/s]

Extracting zip of tmdb_5000_movies.csv...

/var/folders/yq/j2dbx6613tjcnpwcb34hz9vr0000gn/T/ipykernel_37799/2399375892.py:9: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_credits = kagglehub.load_dataset(

Downloading to /Users/ranacopty/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/versions/2/tmdb_5000_credits.csv...

100%|██████████| 7.30M/7.30M [00:00<00:00, 27.1MB/s]

Extracting zip of tmdb_5000_credits.csv...

(4803, 20)
(4803, 4)
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']
['movie_id', 'title', 'cast', 'crew']

## Dataset Inspection

In [6]:
print(df_movies.shape)
print(df_credits.shape)
display(df_movies.head())
display(df_credits.head())
df_movies.info()

(4803, 20)
(4803, 4)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

## Example Movies

In [7]:
examples = ['John Carter', 'The Lone Ranger', 'Green Lantern']

for title in examples:
    row = df_movies[df_movies['title'] == title]
    if len(row) > 0:
        budget = row['budget'].values[0]
        revenue = row['revenue'].values[0]
        print(f"{title}: budget=${budget/1e6:.0f}M, revenue=${revenue/1e6:.0f}M, ratio={revenue/budget:.2f}")

John Carter: budget=$260M, revenue=$284M, ratio=1.09
The Lone Ranger: budget=$255M, revenue=$89M, ratio=0.35
Green Lantern: budget=$200M, revenue=$220M, ratio=1.10

## Usable Movies

In [8]:
usable = df_movies[
    (df_movies['budget'] > 50_000_000) &
    (df_movies['revenue'] > 0)
]
print(f"Usable movies (budget > $50M and revenue > 0): {len(usable)}")

Usable movies (budget > $50M and revenue > 0): 857

## Cast and Crew Info

In [9]:
# Extract director
def get_director(crew_json):
    try:
        crew = json.loads(crew_json)
        for member in crew:
            if member.get('job') == 'Director':
                return member.get('name')
    except:
        return None
    return None

# Extract lead actor = first listed cast member
def get_lead_actor(cast_json):
    try:
        cast = json.loads(cast_json)
        if len(cast) > 0:
            return cast[0].get('name')
    except:
        return None
    return None

# Merge movies and credits
df_all = df_movies.merge(df_credits[['movie_id', 'crew', 'cast']], left_on='id', right_on='movie_id')

df_all['director'] = df_all['crew'].apply(get_director)
df_all['lead_actor'] = df_all['cast'].apply(get_lead_actor)

# valid budget/revenue mask
valid_financials = (df_all['budget'] > 0) & (df_all['revenue'] > 0)

# Flop label
df_all['flop'] = np.nan
df_all.loc[valid_financials, 'flop'] = (
    df_all.loc[valid_financials, 'revenue'] < 2.5 * df_all.loc[valid_financials, 'budget']).astype(int)

# Revenue-to-budget ratio
df_all['rev_budget_ratio'] = np.nan
df_all.loc[valid_financials, 'rev_budget_ratio'] = (
    df_all.loc[valid_financials, 'revenue'] / df_all.loc[valid_financials, 'budget'])

# compute prior track records & number of prior valid films
df_all['release_date'] = pd.to_datetime(df_all['release_date'], errors='coerce')
df_all = df_all.sort_values('release_date').reset_index(drop=True)
df_all['rev_budget_ratio_capped'] = df_all['rev_budget_ratio'].clip(upper=10) # cap so blockbuster does not dominate
df_all['director_success_ratio'] = df_all.groupby('director')['rev_budget_ratio_capped'].transform(
    lambda x: x.shift(1).expanding().mean())
df_all['actor_success_ratio'] = df_all.groupby('lead_actor')['rev_budget_ratio_capped'].transform(
    lambda x: x.shift(1).expanding().mean())
df_all['director_prior_count'] = df_all.groupby('director')['rev_budget_ratio_capped'].transform(
    lambda x: x.shift(1).expanding().count())
df_all['actor_prior_count'] = df_all.groupby('lead_actor')['rev_budget_ratio_capped'].transform(
    lambda x: x.shift(1).expanding().count())

# Filter to mid-to-high-budget films
df = df_all[
    (df_all['budget'] > 50_000_000) &
    (df_all['revenue'] > 0)].copy()

# Fill missing track records
# 1.0 means revenue equals budget, a neutral/default commercial performance value.
df['director_success_ratio'] = df['director_success_ratio'].fillna(1.0)
df['actor_success_ratio'] = df['actor_success_ratio'].fillna(1.0)
# 0 means no prior valid films in the dataset
df['director_prior_count'] = df['director_prior_count'].fillna(0)
df['actor_prior_count'] = df['actor_prior_count'].fillna(0)

# release year for chronological splitting
df['release_year'] = df['release_date'].dt.year

print(f"Final dataset shape: {df.shape}")

print(df[
    ['title', 'release_year', 'director', 'lead_actor',
     'director_success_ratio', 'director_prior_count',
     'actor_success_ratio', 'actor_prior_count',
     'flop']
].head(10).to_string(index=False))

Final dataset shape: (857, 33)
          title  release_year             director            lead_actor  director_success_ratio  director_prior_count  actor_success_ratio  actor_prior_count  flop
     Metropolis          1927           Fritz Lang         Brigitte Helm                1.000000                   0.0             1.000000                0.0   1.0
       Superman          1978       Richard Donner     Christopher Reeve               10.000000                   1.0             1.000000                0.0   0.0
    Superman II          1980       Richard Lester          Gene Hackman               10.000000                   1.0             6.381250                2.0   0.0
The Cotton Club          1984 Francis Ford Coppola          Richard Gere                4.525884                   5.0             1.000000                0.0   1.0
         Ishtar          1987           Elaine May         Warren Beatty                1.000000                   0.0             1.261958                1.0   1.0
      Rambo III          1988      Peter MacDonald    Sylvester Stallone                1.000000                   0.0             6.031176                5.0   0.0
      The Abyss          1989        James Cameron             Ed Harris                9.954499                   2.0             1.000000                0.0   1.0
   Tango & Cash          1989  Andrei Konchalovsky    Sylvester Stallone                1.000000                   0.0             5.526022                6.0   1.0
   Total Recall          1990       Paul Verhoeven Arnold Schwarzenegger                1.000000                   0.0             5.314864                8.0   0.0
Days of Thunder          1990           Tony Scott            Tom Cruise               10.000000                   2.0             6.726007                3.0   0.0

## Data Distribution

In [10]:
print("FLOP vs HIT")
print(f"Total movies: {len(df)}")
print(f"Flops: {int(df['flop'].sum())} ({df['flop'].mean()*100:.1f}%)")
print(f"Hits: {int((df['flop'] == 0).sum())} ({(1 - df['flop'].mean())*100:.1f}%)")

print("\nDIRECTOR TRACK RECORD")
has_real_director = df['director_prior_count'] > 0
print(f"Films with real director track record: {has_real_director.sum()} ({has_real_director.mean()*100:.1f}%)")
print(f"Films with no prior director data: {(~has_real_director).sum()}")

print("\nACTOR TRACK RECORD")
has_real_actor = df['actor_prior_count'] > 0
print(f"Films with real actor track record: {has_real_actor.sum()} ({has_real_actor.mean()*100:.1f}%)")
print(f"Films with no prior actor data: {(~has_real_actor).sum()}")

print("\nSAMPLE ROWS")
print(df[['title', 'release_year', 'director', 'lead_actor',
     'director_success_ratio', 'director_prior_count',
     'actor_success_ratio', 'actor_prior_count',
     'flop']].head(15).to_string(index=False))

FLOP vs HIT
Total movies: 857
Flops: 478 (55.8%)
Hits: 379 (44.2%)

DIRECTOR TRACK RECORD
Films with real director track record: 661 (77.1%)
Films with no prior director data: 196

ACTOR TRACK RECORD
Films with real actor track record: 697 (81.3%)
Films with no prior actor data: 160

SAMPLE ROWS
                     title  release_year             director            lead_actor  director_success_ratio  director_prior_count  actor_success_ratio  actor_prior_count  flop
                Metropolis          1927           Fritz Lang         Brigitte Helm                1.000000                   0.0             1.000000                0.0   1.0
                  Superman          1978       Richard Donner     Christopher Reeve               10.000000                   1.0             1.000000                0.0   0.0
               Superman II          1980       Richard Lester          Gene Hackman               10.000000                   1.0             6.381250                2.0   0.0
           The Cotton Club          1984 Francis Ford Coppola          Richard Gere                4.525884                   5.0             1.000000                0.0   1.0
                    Ishtar          1987           Elaine May         Warren Beatty                1.000000                   0.0             1.261958                1.0   1.0
                 Rambo III          1988      Peter MacDonald    Sylvester Stallone                1.000000                   0.0             6.031176                5.0   0.0
                 The Abyss          1989        James Cameron             Ed Harris                9.954499                   2.0             1.000000                0.0   1.0
              Tango & Cash          1989  Andrei Konchalovsky    Sylvester Stallone                1.000000                   0.0             5.526022                6.0   1.0
              Total Recall          1990       Paul Verhoeven Arnold Schwarzenegger                1.000000                   0.0             5.314864                8.0   0.0
           Days of Thunder          1990           Tony Scott            Tom Cruise               10.000000                   2.0             6.726007                3.0   0.0
                Die Hard 2          1990         Renny Harlin          Bruce Willis                5.136425                   2.0             5.027427                1.0   0.0
   The Godfather: Part III          1990 Francis Ford Coppola             Al Pacino                3.625073                   7.0             4.042765                3.0   0.0
               Hudson Hawk          1991      Michael Lehmann          Bruce Willis                1.000000                   0.0             4.228221                2.0   1.0
Terminator 2: Judgment Day          1991        James Cameron Arnold Schwarzenegger                7.064904                   3.0             5.653919               10.0   0.0
                      Hook          1991     Steven Spielberg        Robin Williams                8.164864                   9.0             9.766245                2.0   0.0

In [11]:
# Yearly distribution after final filtering
df['release_year'] = df['release_date'].dt.year

yearly_dist = (
    df.groupby('release_year')
      .agg(
          total_movies=('title', 'count'),
          flops=('flop', 'sum'),
          hits=('flop', lambda x: (x == 0).sum()),
          flop_rate=('flop', 'mean')
      )
      .reset_index()
)

yearly_dist['flop_rate'] = (yearly_dist['flop_rate'] * 100).round(1)

print("YEARLY DISTRIBUTION")
print(yearly_dist.to_string(index=False))

YEARLY DISTRIBUTION
 release_year  total_movies  flops  hits  flop_rate
         1927             1    1.0     0      100.0
         1978             1    0.0     1        0.0
         1980             1    0.0     1        0.0
         1984             1    1.0     0      100.0
         1987             1    1.0     0      100.0
         1988             1    0.0     1        0.0
         1989             2    2.0     0      100.0
         1990             4    0.0     4        0.0
         1991             3    1.0     2       33.3
         1992             2    0.0     2        0.0
         1993             3    1.0     2       33.3
         1994             6    1.0     5       16.7
         1995            14    7.0     7       50.0
         1996            17   10.0     7       58.8
         1997            26   15.0    11       57.7
         1998            32   18.0    14       56.2
         1999            36   28.0     8       77.8
         2000            37   22.0    15       59.5
         2001            42   27.0    15       64.3
         2002            42   22.0    20       52.4
         2003            39   26.0    13       66.7
         2004            42   25.0    17       59.5
         2005            38   27.0    11       71.1
         2006            42   27.0    15       64.3
         2007            36   21.0    15       58.3
         2008            48   28.0    20       58.3
         2009            42   28.0    14       66.7
         2010            49   27.0    22       55.1
         2011            45   18.0    27       40.0
         2012            43   20.0    23       46.5
         2013            48   28.0    20       58.3
         2014            45   17.0    28       37.8
         2015            41   16.0    25       39.0
         2016            27   13.0    14       48.1

In [12]:
train = df[df['release_year'] < 2010]
val = df[(df['release_year'] >= 2010) & (df['release_year'] <= 2013)]
test = df[df['release_year'] >= 2014]

print("SPLIT DISTRIBUTION")
for name, split in [('Train (<2010)', train),
                    ('Validation (2010-2013)', val),
                    ('Test (2014+)', test)]:
    print(f"\n{name}")
    print(f"Movies: {len(split)}")
    print(f"Flops: {split['flop'].sum()} ({split['flop'].mean()*100:.1f}%)")
    print(f"Hits: {(split['flop']==0).sum()} ({(1-split['flop'].mean())*100:.1f}%)")
    print(f"Years: {split['release_year'].min()} - {split['release_year'].max()}")

SPLIT DISTRIBUTION

Train (<2010)
Movies: 559
Flops: 339.0 (60.6%)
Hits: 220 (39.4%)
Years: 1927 - 2009

Validation (2010-2013)
Movies: 185
Flops: 93.0 (50.3%)
Hits: 92 (49.7%)
Years: 2010 - 2013

Test (2014+)
Movies: 113
Flops: 46.0 (40.7%)
Hits: 67 (59.3%)
Years: 2014 - 2016